version: '3.8'

services:
  app:
    build: .
    ports:
      - "8088:8088"
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/SOSAuto?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=TAHAtaha
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQLDialect
      - SECURITY_JWT_SECRET_KEY=1HXHqNRFKtJzbnoSCDonruEp6rbWkU6q03CYhl00lP4boLcJiB5WqPwjoNj8ab7
    networks:
      - backend-network

  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=TAHAtaha
      - MYSQL_DATABASE=SOSAuto
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend-network

volumes:
  mysql-data:

networks:
  backend-network:
    driver: bridge