version: "3.8"

services:
  cleandar-db:
    image: postgres
    container_name: cleandar-db
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=cleanDar
    ports:
      - '5432:5432'

  cleandar:
    container_name: cleanDar-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8082:8082'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://cleandar-db:5432/cleanDar
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - cleandar-db